spring:
  firstDatasource:
    username: root
    url: jdbc:mysql://localhost:3306/transmaster_transport_db?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  secondDatasource:
    username: root
    url: jdbc:mysql://localhost:3306/backup_db?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    rest:
      base-path: /api
  thymeleaf:
    cache: false
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
#    show-sql: true
parser:
  json-data-dir: /Users/Roman/Desktop
  backup-dir: /Users/Roman/Desktop/backup
  response-dir: /Users/Roman/Desktop/response
logging:
  path: /Users/Roman/Desktop/logs