spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/transmaster_transport_db?useSSL=false
    password: MyNewPass
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    rest:
      base-path: /api
  thymeleaf:
    cache: false
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
parser:
  json-data-dir: /home/user/ed/sbatlogistru-java/src/main/resources/templates/angular
  logs-dir: /home/pigin_s/exchange/logs
  backup-dir: /home/pigin_s/exchange/backup
  response-dir: /home/pigin_s/exchange/parser-response